#!/bin/bash

# Note: This file is not part of the hypre distribution provided by the hypre
# development group at Lawrence Livermore National Laboratory.  It is
# provided by the authors of WARP3D to aid users in compiling the hypre
# library on their system.

# Script cleans up hypre, both in the hypre source directories and in
# the relevant WARP directories.

# Check to make sure WARP3D_HOME is set
[ -z "$WARP3D_HOME" ] && echo "Need to set WARP3D_HOME before proceeding." && exit 1

# cd for you
cd $WARP3D_HOME/linux_packages/source/hypre-2.9.0b

# Clean up hypre
cd src
make clean

