#!/bin/bash

# Note: This file is not part of the metis package.  It is provided by
# the authors of WARP3D to aid users in compiling the metis library
# on their system.

# Clean up the metis directory and the library folder in WARP

# Check to make sure WARP3D_HOME is set
[ -z "$WARP3D_HOME" ] && echo "Need to set WARP3D_HOME before proceeding." && exit 1

# Move directories for you if required
cd $WARP3D_HOME/linux_packages/source/metis-4.0

# Clean the metis directory
rm -f graphchk kmetis mesh2* oemetis onmetis partdmesh partnmesh pmetis libmetis.a

# Clean metis objects
make clean

