#!/bin/bash

#**************************************************************
#*                                                            *
#*      cleanup_files                                         *
#*                                                            *
#**************************************************************

function cleanup_files {
#
/bin/rm -f  *_out out* we* wn* >& /dev/null
/bin/rm -f  *~ >& /dev/null
/bin/rm -f energy  >& /dev/null
/bin/rm -f *_db >& /dev/null
#
}

#**************************************************************
#*                                                            *
#*      run_and_compare                                       *
#*                                                            *
#**************************************************************

function run_and_compare {
#
echo "  ... running testF_1...(alpha w/ material definition)"
"$warp3d_exe" $num_threads  < warp3d_1_alpha_with_material.inp > out_1a
echo "  ... running testF_2...(Anisotropic alphas)"
"$warp3d_exe"  $num_threads < warp3d_2_anisotropic.inp > out_1b
echo "  ... running testF_3...(FGMs)"
"$warp3d_exe"  $num_threads  < warp3d_3_fgm_alpha.inp > out_1c
echo "  ... running testF_4...(Face Loading)"
"$warp3d_exe"  $num_threads  < warp3d_4_face_loading.inp > out_1d
#
echo "  ... WARP3D jobs completed..."

#
perl check_1a.perl
perl check_1b.perl
perl check_1c.perl
perl check_1d.perl
#
cleanup_files
#
}


#**************************************************************
#*                                                            *
#*      main programs                                         *
#*                                                            *
#**************************************************************
#
echo " "; echo " ";
#
machine=`uname`
echo ">> machine id: " $machine
num_threads=$NUM_THREADS
cleanup_files
#
if [ "$MACHINE_TYPE" = '0' ]; then
   echo -e "\n   OSX and Linux verification..."
   warp3d_exe="$WARP3D_EXE"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '1' ]; then
   echo -e "\n  Windows 32-bit verification..."
   warp3d_exe="$WARP3D_EXE_32"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '2' ]; then
   echo -e "\n  Windows verification..."
   warp3d_exe="$WARP3D_EXE_64"
   run_and_compare
fi
#
#
exit
