#!/bin/bash

#**************************************************************
#*                                                            *
#*      cleanup_files                                         *
#*                                                            *
#**************************************************************

function cleanup_files {
#
rm -f  *_out  woutp* *.db >& /dev/null
rm -f  *~ >& /dev/null
rm -f energy  >& /dev/null
rm -f *_db >& /dev/null
rm -f wn*  >& /dev/null
rm -f we*  >& /dev/null
rm -f step*.rest  >& /dev/null
rm -f cvn.batch_messages >& /dev/null
rm -f states* >& /dev/null
#
}

#**************************************************************
#*                                                            *
#*      run_and_compare                                       *
#*                                                            *
#**************************************************************

function run_and_compare {
#
echo "  ... running..."
export MKL_NUM_THREADS=$threads_warp3d
"$warp3d" $ranks_warp3d $threads_warp3d < warp3d_mts_multi.inp >woutput1
echo "  ... running restart job..."
"$warp3d" $ranks_warp3d $threads_warp3d < restart.inp >woutput2

#
echo "  ... WARP3D job completed ..."
#
# Check
#
perl check.perl
#
# cleanup_files
printf ">>> All done\n"
cleanup_files
#
}

#**************************************************************
#*                                                            *
#*      Main program                                          *
#*                                                            *
#**************************************************************
run_and_compare
