#!/bin/bash
# Check environment variable
if [ -z "$WARP3D_HOME" ]; then
   printf "[ERROR]\n"
   printf "... Environment variable WARP3D_HOME is not set.\n"
   printf "Quitting...\n"
   exit 1
fi
#
# cd here
cd $WARP3D_HOME/pat_combine

rm -f *.mod
