#!/bin/bash
#
# Check WARP3D_HOME
if [ -z "$WARP3D_HOME" ]; then
   printf "[ERROR]\n"
   printf "... Environment variable WARP3D_HOME is not set.\n"
   printf "Quitting...\n"
   exit 1
fi
#
cd $WARP3D_HOME
#
file_1="https://www.dropbox.com/s/4erh4ccgft475b1/warp3d_external_libs_2021_Sept.zip?dl=0"
#
wget --no-check-certificate -O warp3d_external_libs_2021_Sept.zip $file_1
#
unzip warp3d_external_libs_2021_Sept.zip
#
mkdir ./linux_packages >& /dev/null
#
cd warp3d_external_libs_2021_Sept
cp -a include $WARP3D_HOME/linux_packages/
cp -a lib $WARP3D_HOME/linux_packages/
cp -a OSX_MKL_files $WARP3D_HOME
#
cd $WARP3D_HOME
#
/bin/rm -r ./warp3d_external_libs_2021_Sept
/bin/rm -r ./warp3d_external_libs_2021_Sept.zip
#
exit


