#!/bin/bash

# Check WARP3D_HOME
if [ -z "$WARP3D_HOME" ]; then
   printf "[ERROR]\n"
   printf "... Environment variable WARP3D_HOME is not set.\n"
   printf "Quitting...\n"
   exit 1
fi

cd $WARP3D_HOME


file_1="https://www.dropbox.com/s/le4sbt3yltevwc8/warp3d_external_libs.tar.gz?dl=0"

#wget http://warp3d.googlecode.com/files/warp_external_libs.tar.gz $file_1
wget --no-check-certificate -O warp_external_libs.tar.gz $file_1
tar xvzf warp_external_libs.tar.gz
rm warp_external_libs.tar.gz
cp -r warp_external_libs/include linux_packages/
cp -r warp_external_libs/lib linux_packages/
rm -r warp_external_libs
