#!/bin/bash
#
# Check WARP3D_HOME
if [ -z "$WARP3D_HOME" ]; then
   printf "[ERROR]\n"
   printf "... Environment variable WARP3D_HOME is not set.\n"
   printf "Quitting...\n"
   exit 1
fi
#
cd $WARP3D_HOME
#
file_1="https://www.dropbox.com/scl/fi/0p9rdz9f0ik1z1zhq5qc7/warp3d_external_libs_2026_April.zip?rlkey=4yh407syaui2l2zidpvz6egyr&dl=0"
#
wget --no-check-certificate -O warp3d_external_libs_2026_April.zip $file_1
#
unzip warp3d_external_libs_2026_April.zip
#
mkdir ./linux_packages >& /dev/null
#
cd warp3d_external_libs_2026_April
cp -a lib $WARP3D_HOME/linux_packages/
cp -a OSX_MKL_files $WARP3D_HOME
cp -a MUMPS_libs $WARP3D_HOME
#
cd $WARP3D_HOME
#
/bin/rm -r ./warp3d_external_libs_2026_April 
/bin/rm -r ./warp3d_external_libs_2026_April.zip
#
exit


