#!/bin/bash
#
#
#    Run WARP3D on Linux (gfortran) -- OpenMP only + MKL sparse solver
#    =================================================================
#
#    usage: warp3d_linux_gfortran  ( number of threads )   ( < input ) ( > output )
#
#           ( ) -- optional
#
#
if [ $# = "0" ]; then
   echo ">> Usage:"; echo " "
   echo " warp3d_linux_gfortran ( <parms> )     ( < input ) ( > output )"; echo " "
   echo " <parms>: <no. of threads>  "
   echo "  ( )  implies optional"
   echo " "
   exit 1
fi
#
echo " "
echo ">> Running WARP3D on Linux (gfortran)..."
echo "   OpenMP + threaded MKL direct/iterative sparse solver "
#
if [ -z "$WARP3D_HOME" ]; then
   printf "[ERROR]\n"
   printf "... An environment variable WARP3D_HOME is not set.\n"
   printf "Quitting...\n"
   exit 1
fi
#
#           gfortran must be installed. WARP3D needs shared libraries
#           that are part of gfotran. hope to make static executable
#           at some point.
#
gfort_present=`which gfortran | wc -l`
if (( $gfort_present == 0 )); then
   printf "[ERROR]\n"
   printf "... gfortran must be installed on your system.\n"
   printf "Quitting...\n"
   exit 1
fi
#
#           location of WARP3D distribution linux_packages directory
#           with MKL files.
#           set executable file name for OpenMP + MKL sparse solver
#           version of warp3d
#
export LD_LIBRARY_PATH=$WARP3D_HOME/linux_packages/lib:$LD_LIBRARY_PATH
warp3d_exe="$WARP3D_HOME/run_linux/warp3d_gfortran.omp"
#
#           set the number of threads for WARP3D execution and
#           for use by the MKL sparse direct/iterative solver. Here we just
#           assign the same number of threads for both.
#           default to 1 thread if user does nothing.
#
export OMP_NUM_THREADS=1
if [ $# = "1"  ]; then
    export OMP_NUM_THREADS=$1
fi
export MKL_NUM_THREADS=$OMP_NUM_THREADS
#
echo ">> Number of threads for parallel execution: " $OMP_NUM_THREADS
echo " "
#
touch core &> /dev/null
chmod ugo-rwx core
#
#           may need to be larger on some distros
#
ulimit -s 32768
$warp3d_exe
#
/bin/rm -f core
exit



