#!/bin/bash
#
#
#    Run WARP3D on macOS -- OpenMP only + MKL sparse solver
#    =====================================================
#
#    usage: warp3d_script_macOS ( number of threads )   ( < input ) ( > output )
#
#           ( ) -- optional
#
#
if [ $# = "0" ]; then
   echo ">> Usage:"; echo " "
   echo " warp3d_script_macOS ( <parms> )     ( < input ) ( > output )"; echo " "
   echo " <parms>: <no. of threads>  "
   echo "  ( )  implies optional"
   echo " "
   exit 1
fi
#
#              set the platform: Intel or silicon
#
if [[ "$(uname -m)" == "arm64" ]]; then
    platform="silicon"
else
    platform="intel"
fi
#
echo " "
if [[ "$platform" == "silicon" ]]; then
    echo ">> Running WARP3D on macOS ... Apple silicon"
elif [[ "$platform" == "intel" ]]; then
    echo ">> Running WARP3D on macOS ...Intel"
else
    echo "unknown platform: $platform"
fi
#
if [ -z "$WARP3D_HOME" ]; then
   printf "[ERROR]\n"
   printf "... An environment variable WARP3D_HOME is not set.\n"
   printf "... use Bash shell command: export WARP3D_HOME=... install directory...\n"
   printf "Quitting...\n"
   exit 1
fi
#
#           set executable file name 
#
warp3d_exe="$WARP3D_HOME/run_macOS/warp3d_Intel.exe"
if [[ "$platform" == "silicon" ]]; then
    warp3d_exe="$WARP3D_HOME/run_macOS/warp3d_silicon.exe"
fi
#
if [[ ! -f "$warp3d_exe" ]]
then
    echo " "; echo " "
    echo ">>>> WARP3D executable does not exist:'$warp3d_exe'"
    echo "     No execution possible"
    echo " "; echo " "
    exit
fi
if [[ ! -x "$warp3d_exe" ]]
then
    echo " "; echo " "
    echo ">>>> WARP3D executable must have execute permissions:'$warp3d_exe'"
    echo "     No execution possible"
    echo " "; echo " "
    exit
fi
#
#           set the number of threads for WARP3D execution and
#           for use by the MKL sparse direct/iterative solver. Here we just
#           assign the same number of threads for both.
#           default to 1 thread if user does nothing.
#
export OMP_NUM_THREADS=1
if [ $# = "1"  ]; then
    export OMP_NUM_THREADS=$1
fi
export MKL_NUM_THREADS=$OMP_NUM_THREADS
#
echo ">> Number of threads for parallel execution: " $OMP_NUM_THREADS
echo " "
#
touch core &> /dev/null
chmod ugo-rwx core
#
ulimit -s 32768
$warp3d_exe
#
/bin/rm -f core
exit



