#!/bin/bash

#**************************************************************
#*                                                            *
#*      cleanup_files                                         *
#*                                                            *
#**************************************************************

function cleanup_files {
#
/bin/rm -f  *_out out* *.neu* we* wn* >& /dev/null
/bin/rm -f  *~ >& /dev/null
/bin/rm -f energy  >& /dev/null
/bin/rm -f *_db >& /dev/null
#
}

#**************************************************************
#*                                                            *
#*      run_and_compare                                       *
#*                                                            *
#**************************************************************

function run_and_compare {
#
echo "      Eigenstrain method to impose residual stresses"
echo "  ... running testP_1...(pre-cracked, linear-elastic)"
"$warp3d_exe"  $num_threads < warp3d_1.inp > out_1
echo "  ... running testP_2...(crack after step 1, linear-elastic)"
"$warp3d_exe"  $num_threads < warp3d_2.inp > out_2
echo "  ... running testP_3...(nonlinear, crack after step 1)"
"$warp3d_exe"  $num_threads < warp3d_3.inp > out_3
echo "  ... running testP_4...(nonlinear, using residual stresses)"
"$warp3d_exe"  $num_threads < warp3d_4.inp > out_4
echo "  ... running testP_5...(mises, eigenstrains)"
"$warp3d_exe"  $num_threads < warp3d_5.inp > out_5
echo "  ... running testP_5...(mises, residual stresses)"
"$warp3d_exe"  $num_threads < warp3d_5a.inp > out_5a
echo "  ... running testP_6...(cyclic, eigenstrains)"
"$warp3d_exe"  $num_threads < warp3d_6.inp > out_6
echo "  ... running testP_6a...(cyclic, residual stresses)"
"$warp3d_exe"  $num_threads < warp3d_6a.inp > out_6a
echo "  ... running testP_7...(deformation plasticity, eigenstrains)"
"$warp3d_exe"  $num_threads < warp3d_7.inp > out_7
echo "  ... WARP3D jobs completed..."
#
perl check_1.perl
perl check_2.perl
perl check_3.perl
perl check_4.perl
perl check_5.perl
perl check_5a.perl
perl check_6.perl
perl check_6a.perl
perl check_7.perl
#
cleanup_files
#
}


#**************************************************************
#*                                                            *
#*      main programs                                         *
#*                                                            *
#**************************************************************
#
echo " "; echo " ";
#
machine=`uname`
echo ">> machine id: " $machine
num_threads=$NUM_THREADS
cleanup_files
#
if [ "$MACHINE_TYPE" = '0' ]; then
   echo -e "\n   OSX and Linux verification..."
   warp3d_exe="$WARP3D_EXE"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '1' ]; then
   echo -e "\n  Windows 32-bit verification..."
   warp3d_exe="$WARP3D_EXE_32"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '2' ]; then
   echo -e "\n  Windows verification..."
   warp3d_exe="$WARP3D_EXE_64"
   run_and_compare
fi
#
#
exit
