#!/bin/bash

#**************************************************************
#*                                                            *
#*      cleanup_files                                         *
#*                                                            *
#**************************************************************

function cleanup_files {
#
/bin/rm -f  *_out out* we* wn* >& /dev/null
/bin/rm -f  *~ >& /dev/null
/bin/rm -f energy  >& /dev/null
/bin/rm -f *_db >& /dev/null
#
}

#**************************************************************
#*                                                            *
#*      run_and_compare                                       *
#*                                                            *
#**************************************************************

function run_and_compare {
#
echo "      20-node SE(B) tests plane-strain, blunt front"
echo "  ... running testI_1...(linear elastic, no FGMS -- J7, J8 zero)"
"$warp3d_exe"  $num_threads < warp3d_1.inp > out_1
echo "  ... running testI_2...(linear elastic, FGMs -- J7, J8 not zero)"
"$warp3d_exe"  $num_threads < warp3d_2.inp > out_2
echo "  ... running testI_3...(deformation plasticity, no FGMs -- J7, J8 zero)"
"$warp3d_exe"  $num_threads < warp3d_3.inp > out_3
echo "  ... running testI_4...(deformation plasticity, w/ FGMs -- J7, J8 not zero)"
"$warp3d_exe"  $num_threads < warp3d_4.inp > out_4
echo "  ... running testI_5...(mises small strains, no FGMs -- J7, J8 zero)"
"$warp3d_exe"  $num_threads < warp3d_5.inp > out_5
echo "  ... running testI_6...(mises small strains, w/ FGMs -- J7, J8 not zero)"
"$warp3d_exe"  $num_threads < warp3d_6.inp > out_6
#
echo "  ... WARP3D jobs completed..."

#
perl check_1.perl
perl check_2.perl
echo " "
echo "        ... differences in 3-6 are deformation vs. mises and including J7, J8"
perl check_3.perl
perl check_4.perl
perl check_5.perl
perl check_6.perl

#
cleanup_files
#
}


#**************************************************************
#*                                                            *
#*      main programs                                         *
#*                                                            *
#**************************************************************
#
echo " "; echo " ";
#
machine=`uname`
echo ">> machine id: " $machine
num_threads=$NUM_THREADS
cleanup_files
#
if [ "$MACHINE_TYPE" = '0' ]; then
   echo -e "\n   OSX and Linux verification..."
   warp3d_exe="$WARP3D_EXE"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '1' ]; then
   echo -e "\n  Windows 32-bit verification..."
   warp3d_exe="$WARP3D_EXE_32"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '2' ]; then
   echo -e "\n  Windows verification..."
   warp3d_exe="$WARP3D_EXE_64"
   run_and_compare
fi
#
#
exit
