#
# ****************************************************************************
#                                                               
#   File: Makefile        
#                                                               
#   Programmer: Erick Jenkins
#   Date: Sept 2004                                                           
#
#   Description:
#     A g++ makefile to make the WARP3D Makefile Generator Program.
#     (Say it 10 times fast).
#
#
# *****************************************************************************
#
#

all:
	g++ -o makegen.exe makefile_generator.cc
