#!/bin/bash
#
# Script to compile patwarp
#
# Check to make sure WARP3D_HOME is set
[ -z "$WARP3D_HOME" ] && echo "Need to set WARP3D_HOME before proceeding." && exit 1
#
# Move to this directory
cd $WARP3D_HOME/patwarp
#
# Test compiler (no real point in proceeding without ifort)
#
hash ifx 2>&- || { echo >&2 "The Intel fortran compiler is required (ifx).  Aborting."; exit 1;}
#
# Now proceed.
echo "Compiling patwarp on Linux ..."
ifx -O2 -static-intel -fixed -traceback -fpe0 patwarp.f \
       -o $WARP3D_HOME/run_linux/patwarp.exe
#
echo "Executable is in run_linux"
/bin/rm patwarp_data.mod
exit
