#!/bin/bash


#**************************************************************
#*                                                            *
#*      cleanup_files                                         *
#*                                                            *
#**************************************************************

function cleanup_files {
#
/bin/rm -f  test_39_out*
/bin/rm -f  *~ >& /dev/null
/bin/rm -f energy  >& /dev/null
/bin/rm -f *_db >& /dev/null
/bin/rm -f wn*  >& /dev/null
/bin/rm -f we*  >& /dev/null
#
}

#**************************************************************
#*                                                            *
#*      run_and_compare                                       *
#*                                                            *
#**************************************************************

function run_and_compare {
#
echo "  ... running test_39a (CTOA growth)..."
"$warp3d_exe" $num_threads  < test_39a > test_39_outa
#
echo "  ... running test_39b (SMCS growth Type 1)..."
"$warp3d_exe" $num_threads  < test_39b > test_39_outb
#
echo "  ... running test_39c (SMCS growth Type 2)..."
"$warp3d_exe" $num_threads  < test_39c > test_39_outc
#
echo "  ... running test_39c (SMCS growth Type 3)..."
"$warp3d_exe" $num_threads  < test_39d > test_39_outd
echo "  ... WARP3D jobs completed..."
#
perl check_39a.perl
perl check_39b.perl
perl check_39c.perl
perl check_39d.perl
cleanup_files
#
}


#**************************************************************
#*                                                            *
#*      main programs                                         *
#*                                                            *
#**************************************************************
#
echo " "; echo " ";
#
machine=`uname`
echo ">> machine id: " $machine
num_threads=$NUM_THREADS
cleanup_files
#
if [ "$MACHINE_TYPE" = '0' ]; then
   echo -e "   OSX and Linux verification..."
   warp3d_exe="$WARP3D_EXE"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '1' ]; then
   echo -e "\n Windows 32-bit verification..."
   warp3d_exe="$WARP3D_EXE_32"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '2' ]; then
   echo -e "   Windows verification..."
   warp3d_exe="$WARP3D_EXE_64"
   run_and_compare
fi
#
#
echo -e "\n>>> All done with test_39 ...\n\n"
exit
