#!/bin/bash

git commit -m "for version 17.7.0" ./ct_big_cohes
git commit -m "for version 17.7.0" ./ct_big_cohes/input_scalar
git commit -m "for version 17.7.0" ./ct_big_cohes/input_8_cpus
git commit -m "for version 17.7.0" ./steel_bldg_joint
git commit -m "for version 17.7.0" ./steel_bldg_joint/input
git commit -m "for version 17.7.0" ./steel_bldg_joint/domain_def
git commit -m "for version 17.7.0" ./mt_cohes_4_cpu
git commit -m "for version 17.7.0" ./README
git commit -m "for version 17.7.0" ./ct_ctoa
git commit -m "for version 17.7.0" ./ct_ctoa/input_2_procs_a_restart
git commit -m "for version 17.7.0" ./ct_ctoa/input_2_procs
git commit -m "for version 17.7.0" ./ct_ctoa/input_2_procs_a
git commit -m "for version 17.7.0" ./big_cvn_models
git commit -m "for version 17.7.0" ./big_cvn_models/cvn_mpi_16
git commit -m "for version 17.7.0" ./big_cvn_models/cvn_mpi_16/warp3d_input
git commit -m "for version 17.7.0" ./fgm_crack_panel_therm
git commit -m "for version 17.7.0" ./zlist
git commit -m "for version 17.7.0" ./seb_impact_2_domains
git commit -m "for version 17.7.0" ./seb_impact_2_domains/warp3d.inp
git commit -m "for version 17.7.0" ./test_18
git commit -m "for version 17.7.0" ./test_18/test_18_1_domain
git commit -m "for version 17.7.0" ./test_18/test_18_4_domain
git commit -m "for version 17.7.0" ./fgm_crack_panel
git commit -m "for version 17.7.0" ./pipe_crush
git commit -m "for version 17.7.0" ./pipe_crush/restart_2_domains
git commit -m "for version 17.7.0" ./pipe_crush/input_2_domains
git commit -m "for version 17.7.0" ./pipe_crush/patran_neutral
git commit -m "for version 17.7.0" ./pressure_vessel
git commit -m "for version 17.7.0" ./test_13
git commit -m "for version 17.7.0" ./test_13/test_13_8
git commit -m "for version 17.7.0" ./test_13/README
git commit -m "for version 17.7.0" ./test_13/test_13_2
git commit -m "for version 17.7.0" ./test_13/restart_4
git commit -m "for version 17.7.0" ./test_13/restart_2
git commit -m "for version 17.7.0" ./test_13/test_13_4
git commit -m "for version 17.7.0" ./test_13/test_13_1
git commit -m "for version 17.7.0" ./explosive_test
git commit -m "for version 17.7.0" ./explosive_test/input
git commit -m "for version 17.7.0" ./test_1
git commit -m "for version 17.7.0" ./test_1/4_domain_umat
git commit -m "for version 17.7.0" ./test_1/4_domain
git commit -m "for version 17.7.0" ./test_1/README
git commit -m "for version 17.7.0" ./test_1/2_domain
git commit -m "for version 17.7.0" ./test_1/1_domain
git commit -m "for version 17.7.0" ./test_1/cantilever

echo " ....    done  "
exit




git rm  ./ct_big_cohes
git rm  ./ct_big_cohes/input_scalar
git rm  ./ct_big_cohes/input_8_cpus
git rm  ./steel_bldg_joint
git rm  ./steel_bldg_joint/input
git rm  ./steel_bldg_joint/domain_def
git rm  ./mt_cohes_4_cpu
git rm  ./README
git rm  ./ct_ctoa
git rm  ./ct_ctoa/input_2_procs_a_restart
git rm  ./ct_ctoa/input_2_procs
git rm  ./ct_ctoa/input_2_procs_a
git rm  ./big_cvn_models
git rm  ./big_cvn_models/README
git rm  ./big_cvn_models/cvn_mpi_2
git rm  ./big_cvn_models/cvn_mpi_2/warp3d_input
git rm  ./big_cvn_models/cvn_mpi_4
git rm  ./big_cvn_models/cvn_mpi_4/newpat.out
git rm  ./big_cvn_models/cvn_mpi_4/warp3d_input
git rm  ./big_cvn_models/cvn_mpi_16
git rm  ./big_cvn_models/cvn_mpi_16/newpat.out
git rm  ./big_cvn_models/cvn_mpi_16/warp3d_input
git rm  ./big_cvn_models/cvn_mpi_8
git rm  ./big_cvn_models/cvn_mpi_8/newpat.out
git rm  ./big_cvn_models/cvn_mpi_8/warp3d_input
git rm  ./big_cvn_models/cvn.neutral
git rm  ./fgm_crack_panel_therm
git rm  ./seb_impact_2_domains
git rm  ./seb_impact_2_domains/warp3d.inp
git rm  ./test_18
git rm  ./test_18/patran.out
git rm  ./test_18/test_18_1_domain
git rm  ./test_18/test_18_4_domain
git rm  ./fgm_crack_panel
git rm  ./pipe_crush
git rm  ./pipe_crush/restart_2_domains
git rm  ./pipe_crush/input_2_domains
git rm  ./pipe_crush/patran_neutral
git rm  ./pressure_vessel
git rm  ./test_13
git rm  ./test_13/test_13_8
git rm  ./test_13/README
git rm  ./test_13/test_13_2
git rm  ./test_13/restart_4
git rm  ./test_13/restart_2
git rm  ./test_13/test_13_4
git rm  ./test_13/test_13_1
git rm  ./explosive_test
git rm  ./explosive_test/input
git rm  ./explosive_test/patran.neut
git rm  ./test_1
git rm  ./test_1/4_domain_umat
git rm  ./test_1/4_domain
git rm  ./test_1/README
git rm  ./test_1/2_domain
git rm  ./test_1/1_domain

git commit  -m "cleanup for version 17.70"    ./ct_big_cohes
git commit  -m "cleanup for version 17.70"    ./ct_big_cohes/input_scalar
git commit  -m "cleanup for version 17.70"    ./ct_big_cohes/input_8_cpus
git commit  -m "cleanup for version 17.70"    ./steel_bldg_joint
git commit  -m "cleanup for version 17.70"    ./steel_bldg_joint/input
git commit  -m "cleanup for version 17.70"    ./steel_bldg_joint/domain_def
git commit  -m "cleanup for version 17.70"    ./mt_cohes_4_cpu
git commit  -m "cleanup for version 17.70"    ./README
git commit  -m "cleanup for version 17.70"    ./ct_ctoa
git commit  -m "cleanup for version 17.70"    ./ct_ctoa/input_2_procs_a_restart
git commit  -m "cleanup for version 17.70"    ./ct_ctoa/input_2_procs
git commit  -m "cleanup for version 17.70"    ./ct_ctoa/input_2_procs_a
git commit  -m "cleanup for version 17.70"    ./big_cvn_models
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/README
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_2
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_2/warp3d_input
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_4
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_4/newpat.out
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_4/warp3d_input
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_16
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_16/newpat.out
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_16/warp3d_input
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_8
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_8/newpat.out
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn_mpi_8/warp3d_input
git commit  -m "cleanup for version 17.70"    ./big_cvn_models/cvn.neutral
git commit  -m "cleanup for version 17.70"    ./fgm_crack_panel_therm
git commit  -m "cleanup for version 17.70"    ./seb_impact_2_domains
git commit  -m "cleanup for version 17.70"    ./seb_impact_2_domains/warp3d.inp
git commit  -m "cleanup for version 17.70"    ./test_18
git commit  -m "cleanup for version 17.70"    ./test_18/patran.out
git commit  -m "cleanup for version 17.70"    ./test_18/test_18_1_domain
git commit  -m "cleanup for version 17.70"    ./test_18/test_18_4_domain
git commit  -m "cleanup for version 17.70"    ./fgm_crack_panel
git commit  -m "cleanup for version 17.70"    ./pipe_crush
git commit  -m "cleanup for version 17.70"    ./pipe_crush/restart_2_domains
git commit  -m "cleanup for version 17.70"    ./pipe_crush/input_2_domains
git commit  -m "cleanup for version 17.70"    ./pipe_crush/patran_neutral
git commit  -m "cleanup for version 17.70"    ./pressure_vessel
git commit  -m "cleanup for version 17.70"    ./test_13
git commit  -m "cleanup for version 17.70"    ./test_13/test_13_8
git commit  -m "cleanup for version 17.70"    ./test_13/README
git commit  -m "cleanup for version 17.70"    ./test_13/test_13_2
git commit  -m "cleanup for version 17.70"    ./test_13/restart_4
git commit  -m "cleanup for version 17.70"    ./test_13/restart_2
git commit  -m "cleanup for version 17.70"    ./test_13/test_13_4
git commit  -m "cleanup for version 17.70"    ./test_13/test_13_1
git commit  -m "cleanup for version 17.70"    ./explosive_test
git commit  -m "cleanup for version 17.70"    ./explosive_test/input
git commit  -m "cleanup for version 17.70"    ./explosive_test/patran.neut
git commit  -m "cleanup for version 17.70"    ./test_1
git commit  -m "cleanup for version 17.70"    ./test_1/4_domain_umat
git commit  -m "cleanup for version 17.70"    ./test_1/4_domain
git commit  -m "cleanup for version 17.70"    ./test_1/README
git commit  -m "cleanup for version 17.70"    ./test_1/2_domain
git commit  -m "cleanup for version 17.70"    ./test_1/1_domain

echo " ... done ...."