#!/bin/bash

#**************************************************************
#*                                                            *
#*      cleanup_files                                         *
#*                                                            *
#**************************************************************

function cleanup_files {
#
/bin/rm -f  *_out >& /dev/null
/bin/rm -f  gmon* >& /dev/null
/bin/rm -f  woutput >& /dev/null
/bin/rm -f  *~ >& /dev/null
/bin/rm -f energy  >& /dev/null
/bin/rm -f *.db >& /dev/null
/bin/rm -f *.neut >& /dev/null
/bin/rm -f wn* >& /dev/null
/bin/rm -f we* >& /dev/null
#
}

#**************************************************************
#*                                                            *
#*      run_and_compare                                       *
#*                                                            *
#**************************************************************

function run_and_compare {
#
echo " "
echo "  ... running multiple small models to test key CP options..."
echo " "
echo "  ... running test_82: CP w/ Voche option..."
cd voche_model
"$warp3d_exe" $num_threads  < warp3d_voche.inp > woutput
perl check.perl
cleanup_files
cd ..
# 
 echo " "
 echo "  ... running test_82: CP w/ MTS option..."
 cd mts_model
 "$warp3d_exe" $num_threads  < warp3d_mts.inp > woutput
 perl check.perl
 cleanup_files
 cd ..
# 
 echo " "
 echo "  ... running test_82: CP w/ MTS multi-orientation option..."
 cd mts_model_multi
 "$warp3d_exe" $num_threads  < warp3d_mts_multi.inp > woutput
 perl check.perl
 cleanup_files
 cd ..
# 
 echo " "
 echo "  ... running test_82: CP w/ ORNL option (bcc48)..."
 cd ornl_model
 "$warp3d_exe" $num_threads  < warp3d_ornl48.inp > woutput
 perl check.perl
 cleanup_files
 cd ..
# 
 echo " "
 echo "  ... running test_82: CP w/ MRR option..."
 cd mrr_model
 "$warp3d_exe" $num_threads  < warp3d_mrr.inp > woutput
 perl check.perl
 cleanup_files
 cd ..
# 
 echo " "
 echo "  ... running test_82: CP w/ MRR diff1B option..."
 cd mrr_model_diff1B
 "$warp3d_exe" $num_threads  < warp3d_mrr1B.inp > woutput
 perl check.perl
 cleanup_files
 cd ..
# 
 echo " "
 echo "  ... running test_82: CP w/ MRR diff2A option..."
 cd mrr_model_diff2A
 "$warp3d_exe" $num_threads  < warp3d_mrr2A.inp > woutput
 perl check.perl
 cleanup_files
 cd ..
# 
# 
 echo " "
 echo "  ... running test_82: CP w/ MRR diff2B option..."
 cd mrr_model_diff2B
 "$warp3d_exe" $num_threads  < warp3d_mrr2B.inp > woutput
 perl check.perl
 cleanup_files
 cd ..
# 
 echo " "
 echo "  ... running test_82: CP w/ MRR diff3B option..."
 cd mrr_model_diff3B
 "$warp3d_exe" $num_threads  < warp3d_mrr3B.inp > woutput
 perl check.perl
 cleanup_files
 cd ..
# 
 echo " "
 echo "  ... running test_82: CP w/ MRR diff4B option..."
 cd mrr_model_diff4B
 "$warp3d_exe" $num_threads  < warp3d_mrr4B.inp > woutput
 perl check.perl
 cleanup_files
 cd ..
# 
 echo " "
 echo "  ... running test_82: CP w/ DJGM option..."
 cd djgm_model
 "$warp3d_exe" $num_threads  < warp3d_djgm.inp > woutput
 perl check.perl
 cleanup_files
 cd ..
# 

echo " "
echo "  ... running test_82: CP w/ DJGM - Taylor via overlapped elements..."
cd djgm_overlap_taylor
"$warp3d_exe" $num_threads  < warp3d_djgm_overlapped.inp > woutput
perl check.perl
cleanup_files
cd ..


echo " "
echo "  ... running test_82: CP w/ DJGM - Taylor 2 crystals..."
cd djgm_taylor
"$warp3d_exe" $num_threads  < warp3d_djgm_taylor.inp > woutput
perl check.perl
cleanup_files
cd ..


echo " "
echo "  ... running test_82: CP w/ DJGM - Taylor..."
cd djgm_hard_work
"$warp3d_exe" $num_threads  < warp3d_djgm_hard_work.inp > woutput
perl check.perl
cleanup_files
cd ..


#
echo " "
echo "  ... WARP3D jobs completed..."
#
#
cleanup_files
#
}


#**************************************************************
#*                                                            *
#*      main programs                                         *
#*                                                            *
#**************************************************************
#
echo " "; echo " ";
# 
machine=`uname`
echo ">> machine id: " $machine
num_threads=$NUM_THREADS
cleanup_files
#
if [ "$MACHINE_TYPE" = '0' ]; then
   echo -e "   OSX and Linux verification..."
   warp3d_exe="$WARP3D_EXE"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '1' ]; then
   echo -e "\n Windows 32-bit verification..."
   warp3d_exe="$WARP3D_EXE_32"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '2' ]; then
   echo -e "   Windows verification..."
   warp3d_exe="$WARP3D_EXE_64"
   run_and_compare
fi
#
#
echo -e "\n>>> All done with test_82 (CP options)...\n\n"
exit
