#!/bin/sh

# Check for our environment variable
[ -z "$WARP3D_HOME" ] && echo "Need to set WARP3D_HOME before proceeding." && exit 1

# Enter this directory if we aren't already
cd $WARP3D_HOME/linux_packages/source/hypre_code_dir

printf " > Copying hypre code files into src for hypre-enabled WARP3D...\n"
rm ../../../src/iterative_sparse_hypre.f 

cp ./src_sparse_hypre.f ../../../src/iterative_sparse_hypre.f
printf "       iterative_sparse_hypre.f copied\n"
