#!/bin/sh

# Check our env variable
[ -z "$WARP3D_HOME" ] && echo "Need to set WARP3D_HOME before proceeding." && exit 1

# cd into this directory if we haven't
cd $WARP3D_HOME/linux_packages/source/hypre_code_dir

printf " > Copying dummy hypre code files into src for threads-only WARP3D...\n"
rm ../../../src/iterative_sparse_hypre.f 

cp ./dummy_sparse_hypre.f ../../../src/iterative_sparse_hypre.f
printf "       iterative_sparse_hypre.f copied\n"
            
