#!/bin/bash

#**************************************************************
#*                                                            *
#*      cleanup_files                                         *
#*                                                            *
#**************************************************************

function cleanup_files {
#
/bin/rm -f  *_out out* we* wn* *.text >& /dev/null
/bin/rm -f  *~ >& /dev/null
/bin/rm -f energy  >& /dev/null
/bin/rm -f *_db >& /dev/null
#
}

#**************************************************************
#*                                                            *
#*      run_and_compare                                       *
#*                                                            *
#**************************************************************

function run_and_compare {
#
#
#      the 2> /dev/null error re-direction fixes some wierd problem
#      with MPI doing something to STDIN for the shell
#
#
echo "  ... running test (alpha w/ material definition)"
export MKL_NUM_THREADS=$threads_warp3d
"$warp3d" $ranks_warp3d $threads_warp3d <  warp3d_1_alpha_with_material.inp > out_5a
echo "  ... running test (FGM alphas)"
"$warp3d" $ranks_warp3d $threads_warp3d < warp3d_2_fgm_alpha.inp > out_5b

echo "  ... WARP3D jobs completed..."
#
perl check_5a.perl 2> /dev/null
perl check_5b.perl 2> /dev/null

#
cleanup_files
printf ">>> All done\n"
cleanup_files
#
}


#**************************************************************
#*                                                            *
#*      main programs                                         *
#*                                                            *
#**************************************************************
#
run_and_compare

