#!/bin/bash

#**************************************************************
#*                                                            *
#*      cleanup_files                                         *
#*                                                            *
#**************************************************************

function cleanup_files {
#
/bin/rm -f  *_out out* we* wn* *.text >& /dev/null
/bin/rm -f  *~ >& /dev/null
/bin/rm -f energy  >& /dev/null
/bin/rm -f *_db >& /dev/null
#
}

#**************************************************************
#*                                                            *
#*      run_and_compare                                       *
#*                                                            *
#**************************************************************

function run_and_compare {
#
#
#      the 2> /dev/null error re-direction fixes some wierd problem
#      with MPI doing something to STDIN for the shell
#
warp3d_exe=$WARP3D_HOME/warp3d_script_linux_hybrid
echo "  ... running test5_1...(alpha w/ material definition)"
"$warp3d_exe" 4 $num_threads   < warp3d_1_alpha_with_material.inp > out_5a 2> /dev/null
echo "  ... running test5_2...(FGM alphas)"
"$warp3d_exe" 4 $num_threads  < warp3d_2_fgm_alpha.inp > out_5b 2> /dev/null
#
echo "  ... WARP3D jobs completed..."
#
perl check_5a.perl 2> /dev/null
perl check_5b.perl 2> /dev/null

#
cleanup_files
#
}


#**************************************************************
#*                                                            *
#*      main programs                                         *
#*                                                            *
#**************************************************************
#
echo " "; echo " ";
#
machine=`uname`
echo ">> machine id: " $machine
num_threads=$NUM_THREADS
cleanup_files
#
if [ "$MACHINE_TYPE" = '0' ]; then
   echo -e "\n   OSX and Linux verification..."
   warp3d_exe="$WARP3D_EXE"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '1' ]; then
   echo -e "\n  Windows 32-bit verification..."
   warp3d_exe="$WARP3D_EXE_32"
   run_and_compare
fi
if [ "$MACHINE_TYPE" = '2' ]; then
   echo -e "\n  Windows verification..."
   warp3d_exe="$WARP3D_EXE_64"
   run_and_compare
fi
#
#
exit
