#
# ****************************************************************************
#                                                               
#   Makefile.linux      
#
#   Invoked by:    Makewarp.bash script
#
#   Updated:   MArch 25, 2026
#              ** now using Intel ifx compiler **
#              ** MPI deprecated **
#
#   Description:
#     Makefile Header for use with the WARP3D 
#     This header will make an OpenMP Makefile for Linux using the Intel
#     Fortran Compiler (ifort) + MKL systems
#
# *****************************************************************************
#
#
#
#       1. Key compiler options:
#
#           Intel: by default we use the compiler feature to
#                  build instructions in the executable for all
#                  processor tyctions in the executable for all
#                  processor types from ivybridge to current.
#                  During execution the code dispatches the best
#                  instructions for your specific computer.
#
#                  A smaller executable file can be generated using
#                  -xHOST option as offered below
#
#       2. The Pardiso solver package in Intel MKL automatically
#          uses the most efficient instruction set available on
#          your specific computer.
#
#       3. The distributed executables for WARP3D ** require ** 
#          that your processor support the AVX instruction 
#          set from Intel ivybridge and newer processors
#          (as a minimum).
#
#          These processors became available in early 2011 and include:
#             2nd Generation Intel® Core™ i7 Processors
#             2nd Generation Intel® Core™ i5 Processors
#             2nd Generation Intel® Core™ i3 Processors
#             Intel® Xeon® Processor E5 Family
#             Intel® Xeon® Processor E3 Family
#             + all newer processors
#
#           During the next year, we plan to require processors
#           that support the AVX2 instruction set.
#
#       4. We build an executable using shared libraries for 
#          Intel MKL
#
#       We ** strongly ** recommend you re-build the executable to leverage
#       all features of newer x86-64 processors: use the 
#       HARDWARE_SPECIFIC option set rather than the ALL_PROCESSORS set
#       defined below.
#
MAKEFLAGS += -rR
.SUFFIXES:
#
OD = ././../obj_linux
EXE_NAME = warp3d.exe
#
MKL_LIBS = ${WARP3D_HOME}/linux_packages/lib

LIBMKL = -Wl,--start-group ${MKL_LIBS}/libmkl_intel_lp64.a \
         ${MKL_LIBS}/libmkl_intel_thread.a \
         ${MKL_LIBS}/libmkl_core.a \
         -Wl,--end-group   ${MKL_LIBS}/libiomp5.so -lpthread -lm -ldl
#
OSNAME   := Linux
BUILDNUM := 5100
MKL      := MKL
O        = .o
RMC      = /bin/rm -f
MVC      = /bin/mv -f
#
#              common options other than used here:
#                 FTRAP = -ftrapuv -check uninit
#                 INLINE = -inline-level=0
#                 PROFILE = -pg for use with gprof, -g for Intel Adviser
#
FTRAP      =
INLINE     = # -no-inline-factor # -fno-inline
PROFILE    = -g
PROFILE =
OPT_REPORT = -qopt-report=5 -qopt-report-annotate=html -qopt-report-phase=vec
OPT_REPORT = 
OPENMP     = -qopenmp -reentrancy
CHECKFLOAT = -fpe0 -init=snan,arrays -fp-speculation=safe
CHECKFLOAT =
#
ALL_PROCESSORS = -axAVX,CORE-AVX2,COMMON-AVX512 -xIVYBRIDGE \
                 -align array64byte  -qopt-zmm-usage=high
HARDWARE_SPECIFIC = -xHOST  -align array64byte  -qopt-zmm-usage=high
MACHINE_TYPE = $(ALL_PROCESSORS) # $(HARDWARE_SPECIFIC) 
#
FCOPTS = -fpp -O3 -fpconstant -fixed -72 -traceback -ftz $(CHECKFLOAT) \
         $(MACHINE_TYPE) -module $(OD) $(FTRAP) \
         $(INLINE) $(PROFILE) $(OPENMP) 
#
FOR      = ifx $(FCOPTS) -D$(OSNAME) -DMKL -DPARDISO 
LINK     = ifx $(FCOPTS)
#
#               all system level module files that appear as separate *.f
#               in WARP3D
#               => does not include the user routine module .f for Abaqus
#                  compatible routines. see it later down in this file.
#
MODS     := $(OD)/mod_adaptive_steps.o \
			$(OD)/mod_contact.o       \
			$(OD)/mod_crack_growth.o \
			$(OD)/mod_crystals.o \
			$(OD)/mod_damage.o \
			$(OD)/mod_elblk.o \
			$(OD)/mod_eleblocks.o \
			$(OD)/mod_elem_load.o \
			$(OD)/mod_file_info.o \
			$(OD)/mod_jintegral.o \
			$(OD)/mod_local_stiffness.o \
			$(OD)/mod_main.o \
			$(OD)/mod_mpc.o \
			$(OD)/mod_pconvert.o \
			$(OD)/mod_performance.o \
			$(OD)/mod_scan.o       \
			$(OD)/mod_segmental_curves.o \
			$(OD)/mod_stiffness.o \
			$(OD)/mod_trlist.o \
			$(OD)/mod_tan_ek_work_def.o \
			$(OD)/mod_damage_values_def.o \
			$(OD)/mod_user_parms_def.o \
			$(OD)/mod_mm10_working.o \
			$(OD)/mod_sig_eps_work_def.o 
#
INCLUDES := param_def   
#
#                MKL libraries to include at link time. see the
#                initializer scripts that call this makefile script
LIBS = $(LIBMKL) 
#
#                all *.o files for linking.  module files are listed
#                first for readability. try to keep ordering alphabetic
#                after modules
#
OBJ =	 \
	$(OD)/mod_adaptive_steps.o	 \
	$(OD)/mod_contact.o	 \
	$(OD)/mod_crack_growth.o	 \
	$(OD)/mod_crystals.o   \
	$(OD)/mod_damage.o	 \
	$(OD)/mod_elblk.o	 \
	$(OD)/mod_elem_load.o	 \
	$(OD)/mod_eleblocks.o	 \
	$(OD)/mod_file_info.o	 \
	$(OD)/mod_jintegral.o	 \
	$(OD)/mod_local_stiffness.o \
	$(OD)/mod_main.o	 \
	$(OD)/mod_mpc.o	 \
	$(OD)/mod_performance.o \
	$(OD)/mod_pconvert.o	 \
	$(OD)/mod_scan.o	 \
	$(OD)/mod_segmental_curves.o	 \
	$(OD)/mod_stiffness.o	 \
	$(OD)/mod_trlist.o	 \
	$(OD)/user_routines_module.o \
	$(OD)/addifv.o	 \
	$(OD)/addmas.o	 \
	$(OD)/adapt_check.o	 \
	$(OD)/allocate_damage.o	 \
	$(OD)/allocate_load.o	 \
	$(OD)/assemble_code.o	 \
	$(OD)/blcmp1.o	 \
	$(OD)/bmod.o	 \
	$(OD)/chkcrack.o	 \
	$(OD)/chkcrack_ctoa.o	 \
	$(OD)/chkcrack_gurson.o	 \
	$(OD)/chkcrack_smcs.o	 \
	$(OD)/chkcrack_cohesive.o	 \
	$(OD)/chk_stp_reduce.o	 \
	$(OD)/chk_stp_reduce_ctoa.o	 \
	$(OD)/chk_stp_reduce_gurson.o	 \
	$(OD)/chk_stp_reduce_smcs.o	 \
	$(OD)/chk_stp_reduce_cohes.o	 \
	$(OD)/cmpmas.o	 \
	$(OD)/cohes_elem.o	 \
	$(OD)/con_dump.o	 \
	$(OD)/contact.o	 \
	$(OD)/comput.o	 \
	$(OD)/cpu_time.o	 \
	$(OD)/cvtest.o	 \
	$(OD)/derivs.o	 \
	$(OD)/didriv.o	 \
	$(OD)/distup.o	 \
	$(OD)/difrar.o	 \
	$(OD)/di1dsf.o	 \
	$(OD)/dimrot.o	 \
	$(OD)/dicmj.o	 \
	$(OD)/dielem_a.o	 \
	$(OD)/dielem_b.o	 \
	$(OD)/dielem_c.o	 \
	$(OD)/diexp4.o	 \
	$(OD)/dptstf.o	 \
	$(OD)/drive_eps_sig_internal_forces.o	 \
	$(OD)/drive_assemble_solve.o	 \
	$(OD)/drive_pardiso.o	 \
	$(OD)/drive_pardiso_asym.o	 \
	$(OD)/dupmas.o	 \
	$(OD)/dupstr.o	 \
	$(OD)/elmas1.o	 \
	$(OD)/elem_load_a.o	 \
	$(OD)/elem_load_b.o	 \
	$(OD)/elem_load_c.o	 \
	$(OD)/elprp.o	 \
	$(OD)/energy.o	 \
	$(OD)/eqivld.o	 \
	$(OD)/errchk.o	 \
	$(OD)/errmsg.o	 \
	$(OD)/find_neighbors.o	 \
	$(OD)/gatemps.o	 \
	$(OD)/get_edest.o	 \
	$(OD)/growth_loads.o	 \
	$(OD)/gp_temp_eps.o	 \
	$(OD)/gpifv1.o	 \
	$(OD)/gpmas1.o	 \
	$(OD)/gptns1.o	 \
	$(OD)/gtlsn1.o	 \
	$(OD)/gtmat1.o	 \
	$(OD)/incomp.o	 \
	$(OD)/inclmass.o	 \
	$(OD)/incontact.o	 \
	$(OD)/incon.o	 \
	$(OD)/incoor.o	 \
	$(OD)/incrystal.o \
	$(OD)/insurf.o	 \
	$(OD)/intied.o	 \
	$(OD)/indypm.o	 \
	$(OD)/inelbk.o	 \
	$(OD)/inelem.o	 \
	$(OD)/infile.o	 \
	$(OD)/incurv.o	 \
	$(OD)/indom.o	 \
	$(OD)/inalpha.o	 \
	$(OD)/incrack.o	 \
	$(OD)/infgm.o	 \
	$(OD)/inicon.o	 \
	$(OD)/ininc.o	 \
	$(OD)/initdm.o	 \
	$(OD)/initst.o	 \
	$(OD)/inlod.o	 \
	$(OD)/inmat.o	 \
	$(OD)/innum.o	 \
	$(OD)/intab.o	 \
	$(OD)/inpatch.o	 \
	$(OD)/iodevn.o	 \
	$(OD)/kg1.o	 \
	$(OD)/license.o	 \
	$(OD)/linked_list.o	 \
	$(OD)/main_program.o	 \
	$(OD)/mnralg.o	 \
	$(OD)/mem_allocate.o	 \
	$(OD)/mm01.o	 \
	$(OD)/mm02.o	 \
	$(OD)/mm03.o	 \
	$(OD)/mm04.o	 \
	$(OD)/mm05.o	 \
	$(OD)/mm06.o	 \
	$(OD)/mm07.o	 \
	$(OD)/mm08.o	 \
	$(OD)/mm09.o	 \
	$(OD)/mm10_a.o	 \
	$(OD)/mm10_b.o	 \
	$(OD)/mm10_c.o	 \
	$(OD)/mm10_d.o	 \
	$(OD)/mm10_e.o	 \
	$(OD)/mm10_f.o   \
	$(OD)/mm11.o       \
	$(OD)/mmnoopt.o	\
	$(OD)/mm_return_values.o	\
	$(OD)/mpc_modify.o	 \
	$(OD)/name_strip.o	 \
	$(OD)/nasa_vss.o	 \
	$(OD)/nasa_sparse_adj.o	 \
	$(OD)/nasa_sparse_check.o	 \
	$(OD)/nasa_sparse_factor.o	 \
	$(OD)/nasa_sparse_fill.o	 \
	$(OD)/nasa_sparse_loadpass.o	 \
	$(OD)/nasa_sparse_reorder_a.o	 \
	$(OD)/nasa_sparse_reorder_b.o	 \
	$(OD)/nasa_sparse_sym_fact.o	 \
	$(OD)/ndpts1.o	 \
	$(OD)/ouddpa.o	 \
	$(OD)/oudriv.o	 \
	$(OD)/oudups.o	 \
	$(OD)/oudva.o	 \
	$(OD)/ouext1.o	 \
	$(OD)/ouext2.o	 \
	$(OD)/ouflnm.o	 \
	$(OD)/ougts1.o	 \
	$(OD)/ouhdva.o	 \
	$(OD)/ouhel.o	 \
	$(OD)/ouhnod.o	 \
	$(OD)/ouhprn.o	 \
	$(OD)/ouhrks.o	 \
	$(OD)/ouhstr.o	 \
	$(OD)/oulbdd.o	 \
	$(OD)/oulbir.o	 \
	$(OD)/oulbst.o	 \
	$(OD)/oulg1.o	 \
	$(OD)/oumkcv.o	 \
	$(OD)/oundhd.o	 \
	$(OD)/ounds1.o	 \
	$(OD)/ouocdd.o	 \
	$(OD)/ouocst.o	 \
	$(OD)/ouneut.o	 \
	$(OD)/ouocst_elem.o	 \
	$(OD)/oupdva.o	 \
	$(OD)/oupele.o	 \
	$(OD)/ouprks.o	 \
	$(OD)/oupstr_elem.o	 \
	$(OD)/oupstr_node.o	 \
	$(OD)/oures.o	 \
	$(OD)/ourlhd.o	 \
	$(OD)/ousthd.o	 \
	$(OD)/oust_elem.o	 \
	$(OD)/oustates.o	 \
	$(OD)/outfil.o	 \
	$(OD)/oustr.o	 \
	$(OD)/outime.o	 \
	$(OD)/packets.o	 \
	$(OD)/pconvert.o	 \
	$(OD)/prcsel.o	 \
	$(OD)/qmply1.o	 \
	$(OD)/getgpts.o	 \
	$(OD)/read_damage.o	 \
	$(OD)/read_write.o	 \
	$(OD)/reopen.o	 \
	$(OD)/rknifv.o	 \
	$(OD)/rknmas.o	 \
	$(OD)/rknstr.o	 \
	$(OD)/rktstf.o	 \
	$(OD)/rplstr.o	 \
	$(OD)/rscmp1.o	 \
	$(OD)/rstgp1.o	 \
	$(OD)/scan.o	 \
	$(OD)/scstr.o	 \
	$(OD)/setelb.o	 \
	$(OD)/setup.o	 \
	$(OD)/shapef.o	 \
	$(OD)/setup_mat_props.o	 \
	$(OD)/splunj.o	 \
	$(OD)/statistics.o	 \
	$(OD)/steptime.o   \
	$(OD)/store.o	 \
	$(OD)/stpdrv.o	 \
	$(OD)/star_com.o	 \
	$(OD)/tanstf.o	 \
	$(OD)/temsto.o	 \
	$(OD)/thyme.o	 \
	$(OD)/trnvec.o	 \
	$(OD)/trnmtx.o	 \
	$(OD)/tied_mesh_a.o	 \
	$(OD)/tied_mesh_b.o	 \
	$(OD)/tied_mesh_c.o	 \
	$(OD)/tilde.o	 \
	$(OD)/update.o	 \
	$(OD)/uppbar.o	 \
	$(OD)/upres.o	 \
	$(OD)/user_list.o	 \
	$(OD)/user_routines_umat.o	 \
	$(OD)/user_routines_other_Abaqus.o \
	$(OD)/user_routines_warp3d.o	 \
	$(OD)/user_routines_support.o	 \
	$(OD)/vol_terms.o	 \
	$(OD)/vol_avg.o	 \
	$(OD)/zero_vector.o	 \
	$(OD)/zero_vol.o
#
$(EXE_NAME) : $(OBJ)
	$(LINK) $(OBJ) $(LIBS) -o $@
	$(MVC) $@ ./../run_linux/$@
	chmod ugo+rx  ./../run_linux/$@
#
#       ---  default rule to make .o from .f ------
#            ===============================
#
#            => for simplicity we assume all the *.f depend on all
#               modules, includes, param_def
#
$(OD)/%.o : %.f $(MODS) $(INCLUDES)
	$(RMC)  $@
	$(FOR) $< -c -o $@
#        $(FOR) -qopt-report-file=$<.html $< -c -o $@
#
#
#       ---  main_program.f gets special ifort options ------
#            =========================================
#
$(OD)/main_program$O : main_program.f $(MODS) $(INCLUDES)
	$(FOR) -D$(OSNAME) -DBuild=$(BUILDNUM) -fpp  $< -c -o $@
#
#       ---  any .f files that require non-std compile options ------
#            =================================================
#
 $(OD)/mm10_b$O : mm10_b.f  $(MODS) $(INCLUDES) 
	$(RMC)  $@
	$(FOR)  $(NO_INLINE) $< -c -o $@  
#
#       ---  Abaqus compatible user routines. Listed explicitly for clarity ------
#            ==============================================================
#
  $(OD)/user_routines_module$O : user_routines_module.f
	$(RMC)  $@
	$(FOR)  $(NO_INLINE) $< -c -o $@

  $(OD)/user_routines_umat$O : user_routines_umat.f \
              $(OD)/user_routines_module$O $(OD)/mod_user_parms_def$O
	$(RMC)  $@
	$(FOR) $(NO_INLINE)  $< -c -o $@

  $(OD)/user_routines_other_Abaqus$O : user_routines_other_Abaqus.f \
                                     $(OD)/user_routines_module$O
	$(RMC)  $@
	$(FOR) $(NO_INLINE) $< -c -o $@

  $(OD)/user_routines_warp3d$O : user_routines_warp3d.f  \
                               $(OD)/user_routines_module$O \
                               $(OD)/mod_user_parms_def$O
	$(RMC)  $@
	$(FOR)  $(NO_INLINE)  $< -c -o $@

  $(OD)/user_routines_support$O : user_routines_support.f  \
                                $(OD)/user_routines_module$O \
                                $(OD)/mod_user_parms_def$O
	$(RMC)  $@
	$(FOR)  $(NO_INLINE) $< -c -o $@
#
#
#
#    ------   system level module files ----------------
#             =========================
#
$(OD)/mod_adaptive_steps$O : mod_adaptive_steps.f param_def 
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_contact$O : mod_contact.f param_def 
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_crack_growth$O : mod_crack_growth.f param_def  \
                             $(OD)/mod_main$O $(OD)/mod_eleblocks$O \
                             $(OD)/mod_damage$O
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_crystals$O : mod_crystals.f param_def  $(OD)/mod_main$O
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_damage$O : mod_damage.f param_def 
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_elblk$O : mod_elblk.f param_def
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_eleblocks$O : mod_eleblocks.f param_def
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_elem_load$O : mod_elem_load.f param_def
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_file_info$O : mod_file_info.f param_def 
	$(RMC)  $@
	$(FOR) $< -c -o $@
	
$(OD)/mod_jintegral$O : mod_jintegral.f param_def
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_local_stiffness$O : mod_local_stiffness.f   param_def
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_main$O : mod_main.f param_def 
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_mpc$O : mod_mpc.f param_def
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_pconvert$O : mod_pconvert.f param_def 
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_performance$O : mod_performance.f param_def 
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_scan$O : mod_scan.f
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_segmental_curves$O : mod_segmental_curves.f param_def
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_stiffness$O : mod_stiffness.f param_def
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_trlist$O : mod_trlist.f param_def $(OD)/mod_main$O $(OD)/mod_scan$O
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_sig_eps_work_def$O : mod_sig_eps_work_def.f param_def 
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_tan_ek_work_def$O : mod_tan_ek_work_def.f param_def 
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_damage_values_def$O : mod_damage_values_def.f
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_mm10_working$O : mod_mm10_working.f param_def  \
                             $(OD)/mod_main$O $(OD)/mod_crystals$O
	$(RMC)  $@
	$(FOR) $< -c -o $@

$(OD)/mod_user_parms_def$O : mod_user_parms_def.f param_def 
	$(RMC)  $@
	$(FOR) $< -c -o $@
	
	
	
	
	
	
